export const ROUTES = {
  root: '/',
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  onboarding: '/onboarding',
  profile: '/profile',
  matching: '/matching',
  appointments: '/appointments',
  messaging: '/messaging',
  journey: '/journey',
  resources: '/resources',
  adminBackoffice: '/admin',
  adminCompanies: '/admin/companies',
  adminCompanyCreate: '/admin/companies/new',
  adminCompanyEdit: (companyId: string) => `/admin/companies/${companyId}/edit`,
  adminInternships: '/admin/internships',
};
